name: Update README daily from Monday through Friday

on:
  push:
  workflow_dispatch:
  schedule:
    # "At 08:00 on every day-of-week from Monday through Friday."
    - cron: "0 8 * * 1-5"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Python script to update README
        run: python update_readme.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: GitHub Actions
          author_email: github-actions[bot]@users.noreply.github.com
          force: false
          signoff: false
          message: ':memo: Update README.md with daily countdown'
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
